### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by baschenbrenner** [learn-co-curriculum/python-p3-data-structures-lab#1]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by baschenbrenner** [comment]
Just some ponderings about this lab -
I got a little stuck on the chili pepper for a minute but eventually just copied and pasted from the instructions directly into my code - I didn't know you could do that! I can see students getting stuck there.
Should we add a method that creates a new spice - that would be an easy way to add some more testing to make sure students aren't hard coding solutions. I always worry about one-dimensional testing

**Comment by professor-ben** [comment]
***comment posted on incorrect issue
